GET http://localhost:8100/api/sensors

###
PATCH http://localhost:8100/api/device/sensor1
Content-Type: application/json

{
    "value": 55
}

###
GET http://localhost:8100/api/history/sensor1

###
POST http://localhost:8100/api/sensors
Content-Type: application/json

{
    "id": "Sensor 3",
    "unit": "g/ml",
    "value": 0.1337,
    "type": "sensor"
}