GET http://localhost:8100/api/sensors

###
PATCH http://localhost:8100/api/device/Amoni11
Content-Type: application/json

{
    "value": 0.75
}

###
GET http://localhost:8100/api/history/Amoni11

###
POST http://localhost:8100/api/sensors
Content-Type: application/json

{
    "id": "Sensor 3",
    "unit": "g/ml",
    "value": 0.1337,
    "type": "sensor"
}